# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: jhipsterReactPrototype
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTEzNmM4OWQ1NDJhMWQ0ZmVmNWQ3YzA4YzIwNzhiOTRjNzc1Y2RjOTc0YjU4NjU4MDI1MDY1YTZiZjBhNzE2ZTg3NjBiMzUzYjZjZjE1OTg3MzBmY2FlMGEzNjJmMWU2YmFlMzI3MThhYzY2YjkwMjc3NWQ4MGIwZDU3NGE5ZTE=
